'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import type { CSSProperties } from 'react';
import { Header, SafetyFooter } from './Header';
import { NativeLink } from './NativeLink';
import { useLocale } from './LocaleProvider';
import { DEMO_NARRATIVE, type EvidenceKind, type FactKey, type Observation } from '@/lib/contracts';
import { analyseEvidenceLocally, analyseManualText, createSampleBankStatement, createSampleEvidenceSet, downloadDemoEvidenceKit, stopLocalOcr, type OcrMethod } from '@/lib/client-ocr';
import { buildResponsePackage, downloadComplaintReceipt } from '@/lib/client-export';
import { api, onSaveState, setSessionSecurity } from '@/lib/client-api';

type Row = Record<string, string | number | null>;
type ObservationRow = Observation & { evidenceId: string; evidenceKind: string; filename: string };
type Resolution = { field: FactKey; value: string; normalizedValue: string; resolutionType: 'evidence' | 'manual' | 'unknown'; sourceEvidenceId?: string | null };
type Passport = { coverage: { present: number; total: number }; counts: { passed: number; conflicts: number; missing: number; unknownFacts: number }; checks: Array<{ code: string; status: 'pass' | 'conflict' | 'missing'; titleEn: string; titleHi: string; detailEn: string; detailHi: string }>; facts: Array<{ field: string; resolution: { value?: string; resolutionType?: string } | null; observations: Array<{ filename?: string; value?: string }> }> };
type Bundle = { case: Row; evidence: Row[]; chronology: Row[]; milestones: Row[]; observations: ObservationRow[]; resolutions: Resolution[]; passport: Passport; findings: Row[]; custody: Row[]; exports: Row[]; readiness: { blockers: number; warnings: number; issues: Array<{ severity: 'blocker' | 'warning'; field?: string; messageEn: string; messageHi: string }> }; intake: Row | null; profile: Row | null; submission: Row | null; requests: Row[]; requestResponses: Row[]; events: Row[]; meta?: { caseRevision?: number; savedAt?: number } };
type Pending = { id: string; kind: EvidenceKind; filename: string; file: File; sample: boolean; text: string; observations: Observation[]; ocrMethod: OcrMethod; clientSha256: string; notice?: string };
type ProcessingReceipt = {
  requestId: string | null;
  status: string;
  snapshotFrozen: boolean;
  evidenceChecks: { verified: number; total: number };
  steps: Array<{ step_code: string; status: string; attempt_count: number; completed_at?: number | null }>;
  retries: number;
  audit: { valid: boolean; events: number };
  adapter: { name: string; mode: string; contactedExternalSystem: boolean };
  createdAt: number | null;
  completedAt: number | null;
};
type PreparedPassport = { downloadUrl: string; filename: string };

const FACTS: FactKey[] = ['amount', 'reference', 'recipient', 'institution', 'phone', 'occurred_at'];
const PROFILE = { fullName: 'Sunita Sharma', mobile: '90000 00000', gender: 'female', dateOfBirth: '14/08/1987', relationName: 'Rakesh Sharma', address: '14 Demo Lane, Vijay Nagar', state: 'Madhya Pradesh', district: 'Indore', policeStation: 'Vijay Nagar (Demo)', pincode: '452010' };
const INTAKE = { fraudType: 'fake_kyc', channel: 'upi', lossTiming: 'under_30_minutes', helplineContacted: false, bankContacted: false, delayReason: '', amount: 18499, occurredAt: '2026-08-21T18:42' };
const KIND_COPY: Record<EvidenceKind, [string,string]> = { receipt:['Payment receipt','भुगतान रसीद'],chat:['Scam conversation','ठगी बातचीत'],call_log:['Call log','कॉल लॉग'],bank_statement:['Bank statement','बैंक स्टेटमेंट'] };

export function FinancialFraudJourney({ caseId: suppliedCaseId }: { caseId?: string }) {
  const { pick } = useLocale(); const started = useRef(false); const ocrController = useRef<AbortController | null>(null); const errorRef = useRef<HTMLDivElement | null>(null);
  const [session, setSession] = useState<boolean | null>(null); const [login, setLogin] = useState({ mobile: '90000 00000', otp: '123456' });
  const [caseId, setCaseId] = useState(suppliedCaseId || ''); const [bundle, setBundle] = useState<Bundle | null>(null); const [stage, setStage] = useState(1);
  const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [pending, setPending] = useState<Pending | null>(null);
  const [ocr, setOcr] = useState<{ progress: number; status: string } | null>(null); const [intake, setIntake] = useState({ ...INTAKE });
  const [profile, setProfile] = useState({ ...PROFILE }); const [narrative, setNarrative] = useState(DEMO_NARRATIVE);
  const [facts, setFacts] = useState<Record<FactKey, Resolution>>(() => unknownFacts());
  const [preparedPassport, setPreparedPassport] = useState<PreparedPassport | null>(null); const preparedPassportUrl = useRef<string | null>(null);
  const [saveState, setSaveState] = useState<'idle'|'saving'|'saved'|'retrying'|'offline'>('idle');
  const [lastSavedAt, setLastSavedAt] = useState<number | null>(null);

  const applyBundle = useCallback((next: Bundle) => {
    setBundle(next); if (next.submission) setStage(6); else if (next.profile) setStage(5); else if (next.resolutions.length) setStage(4); else if (next.intake) setStage(3); else setStage(1);
    if (next.intake) setIntake({ fraudType:String(next.case.fraud_type),channel:String(next.case.channel),lossTiming:String(next.intake.loss_timing),helplineContacted:Boolean(next.intake.helpline_contacted),bankContacted:Boolean(next.intake.bank_contacted),delayReason:String(next.intake.delay_reason || ''),amount:Number(next.case.amount || 18499),occurredAt:String(next.case.occurred_at || INTAKE.occurredAt) });
    if (next.profile) setProfile({ fullName:String(next.profile.full_name),mobile:String(next.profile.mobile),gender:String(next.profile.gender),dateOfBirth:String(next.profile.date_of_birth),relationName:String(next.profile.relation_name),address:String(next.profile.address),state:String(next.profile.state),district:String(next.profile.district),policeStation:String(next.profile.police_station),pincode:String(next.profile.pincode) });
    if (next.case.narrative_input) setNarrative(String(next.case.narrative_input)); setFacts(suggestFacts(next));
  }, []);
  const refresh = useCallback(async (id: string) => { const next = await api<Bundle>(`/api/cases/${id}`); applyBundle(next); return next; }, [applyBundle]);

  useEffect(() => onSaveState((next) => { setSaveState(next); if (next === 'saved') setLastSavedAt(Date.now()); }), []);
  useEffect(() => () => { if (preparedPassportUrl.current) URL.revokeObjectURL(preparedPassportUrl.current); }, []);
  useEffect(() => { if (error) errorRef.current?.focus(); }, [error]);
  useEffect(() => { if (started.current) return; started.current = true; void api<{active:boolean;csrfToken?:string}>('/api/session').then(async (value) => { setSessionSecurity(value.csrfToken); setSession(value.active); if (!value.active) return; await openCase(); }).catch(() => setSession(false)); return () => { void stopLocalOcr(); }; async function openCase() { if (suppliedCaseId) { setCaseId(suppliedCaseId); await refresh(suppliedCaseId); return; } const stored = localStorage.getItem('f30_active_case'); if (stored) { try { setCaseId(stored); await refresh(stored); return; } catch { localStorage.removeItem('f30_active_case'); } } const created = await api<{id:string}>('/api/cases',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}); setCaseId(created.id); localStorage.setItem('f30_active_case',created.id); await refresh(created.id); } }, [refresh, suppliedCaseId]);

  async function signIn() { setBusy('login'); setError(''); try { const signed=await api<{csrfToken?:string}>('/api/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(login)}); setSessionSecurity(signed.csrfToken); setSession(true); const created=await api<{id:string}>('/api/cases',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}); setCaseId(created.id); localStorage.setItem('f30_active_case',created.id); await refresh(created.id); } catch (caught) { setError(message(caught)); } finally { setBusy(''); } }
  async function saveIntake() { setBusy('intake'); setError(''); try { const next=await api<Bundle>(`/api/cases/${caseId}/intake`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(intake)}); applyBundle(next); setStage(3); } catch(caught){setError(message(caught));} finally{setBusy('');} }

  async function uploadEvidence(file: File, kind: EvidenceKind, sample = false, autoConfirm = false, safeDataConfirmed = sample) {
    const controller = new AbortController(); ocrController.current = controller; setOcr({progress:0,status:pick('Preparing private reader…','निजी रीडर तैयार हो रहा है…')}); setError('');
    try {
      const local = await analyseEvidenceLocally(file, kind, { sample, signal: controller.signal, onProgress: (value) => setOcr(value) });
      const data=new FormData(); data.set('safeDataConfirmed',String(safeDataConfirmed)); data.set('kind',kind); data.set('file',file); if(sample)data.set('sample','true');
      const uploaded=await api<{id:string;filename:string}>(`/api/cases/${caseId}/evidence`,{method:'POST',body:data});
      const analysis:Pending={id:uploaded.id,kind,filename:uploaded.filename,file,sample,...local};
      if(autoConfirm) await confirmAnalysis(analysis,false); else { setPending(analysis); await refresh(caseId); }
      return analysis;
    } catch (caught) {
      setError(message(caught));
      throw caught;
    } finally { if(ocrController.current===controller)ocrController.current=null; setOcr(null); }
  }
  async function confirmAnalysis(analysis = pending,refreshAfter=true) { if(!analysis)return; await api(`/api/cases/${caseId}/evidence/${analysis.id}/confirm`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ocrText:analysis.text,ocrMethod:analysis.ocrMethod,clientSha256:analysis.clientSha256,observations:analysis.observations})}); setPending(null); if(refreshAfter)await refresh(caseId); }
  async function retryAnalysis() { if(!pending)return; const local=await analyseEvidenceLocally(pending.file,pending.kind,{sample:pending.sample,onProgress:setOcr}); setOcr(null); setPending({...pending,...local}); }
  async function loadDemo() { setBusy('demo'); setError(''); setOcr({progress:.08,status:pick('Preparing the sample screenshots…','नमूना स्क्रीनशॉट तैयार हो रहे हैं…')}); try { if(bundle?.evidence.some((item)=>['receipt','chat','call_log'].includes(String(item.kind)))) throw new Error(pick('Remove existing core evidence before loading the sample.','नमूना लोड करने से पहले मौजूदा मुख्य प्रमाण हटाएँ।')); const samples=await createSampleEvidenceSet(); const analysed=[]; for(let index=0;index<samples.length;index+=1){const sample=samples[index];const local=await analyseEvidenceLocally(sample.file,sample.kind,{sample:true});analysed.push({sample,local});setOcr({progress:.18+((index+1)/samples.length)*.42,status:pick('Checking the prepared details…','तैयार जानकारी जाँची जा रही है…')});} const data=new FormData();data.set('safeDataConfirmed','true');data.set('analyses',JSON.stringify(analysed.map(({sample,local})=>({kind:sample.kind,filename:sample.file.name,ocrText:local.text,ocrMethod:local.ocrMethod,clientSha256:local.clientSha256,observations:local.observations}))));analysed.forEach(({sample})=>data.append('file',sample.file));setOcr({progress:.72,status:pick('Saving all three screenshots together…','तीनों स्क्रीनशॉट साथ में सहेजे जा रहे हैं…')});const latest=await api<Bundle>(`/api/cases/${caseId}/demo-evidence`,{method:'POST',body:data});applyBundle(latest);const suggested=suggestFacts(latest);setFacts(suggested);setOcr({progress:.9,status:pick('Preparing the checked details…','जाँची गई जानकारी तैयार हो रही है…')});await saveFacts(suggested); } catch(caught){setError(message(caught));} finally{setOcr(null);setBusy('');} }
  async function removeEvidence(evidenceId:string){setBusy('remove');setError('');try{await api(`/api/cases/${caseId}/evidence/${evidenceId}`,{method:'DELETE'});await refresh(caseId);}catch(caught){setError(message(caught));}finally{setBusy('');}}
  async function saveFacts(value=facts){const next=await api<Bundle>(`/api/cases/${caseId}/facts`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({facts:FACTS.map((field)=>value[field])})});applyBundle(next);return next;}
  async function saveComplaint(){setBusy('complaint');setError('');try{await api(`/api/cases/${caseId}/draft`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({narrative})});const next=await api<Bundle>(`/api/cases/${caseId}/profile`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(profile)});applyBundle(next);setStage(5);}catch(caught){setError(message(caught));}finally{setBusy('');}}
  async function submit(){setBusy('submit');setError('');try{const queued=await api<Bundle>(`/api/cases/${caseId}/submit`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({consent:true,syntheticConfirmation:true})});applyBundle(queued);setStage(6);const next=await api<Bundle>(`/api/cases/${caseId}/process`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({})});applyBundle(next);localStorage.removeItem('f30_active_case');}catch(caught){setError(message(caught));}finally{setBusy('');}}
  async function retryProcessing(){setBusy('process');setError('');try{const next=await api<Bundle>(`/api/cases/${caseId}/process`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({})});applyBundle(next);}catch(caught){setError(message(caught));}finally{setBusy('');}}
  async function buildPassport(){if(!bundle)return;setBusy('export');setError('');try{const latest=await api<Bundle>(`/api/cases/${caseId}/passport`);applyBundle(latest);const prepared=await buildResponsePackage(caseId,latest);if(preparedPassportUrl.current)URL.revokeObjectURL(preparedPassportUrl.current);preparedPassportUrl.current=prepared.downloadUrl;setPreparedPassport({downloadUrl:prepared.downloadUrl,filename:prepared.filename});}catch(caught){setError(message(caught));}finally{setBusy('');}}
  async function answerRequest(customFile?:File,safeDataConfirmed=false){const open=bundle?.requests.find((item)=>item.status==='open');if(!open)return;setBusy('followup');setError('');try{const file=customFile||await createSampleBankStatement();const isSample=!customFile;const analysis=await uploadEvidence(file,'bank_statement',isSample,true,isSample||safeDataConfirmed);const next=await api<Bundle>(`/api/cases/${caseId}/requests/${open.id}/respond`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({evidenceId:analysis.id,note:isSample?'Sample bank statement added by the demo citizen.':'Citizen-provided safe test statement added.'})});applyBundle(next);}catch(caught){setError(message(caught));}finally{setBusy('');}}

  if(session===null) return <Loading text={pick('Opening FIRST30…','FIRST30 खुल रहा है…')} />;
  if(!session) return <Login value={login} setValue={setLogin} submit={signIn} busy={busy==='login'} error={error} pick={pick} />;
  if(!bundle) return <Loading text={error || pick('Opening your saved report…','आपकी सहेजी रिपोर्ट खुल रही है…')} />;
  if(stage===6 && bundle.submission) return <Tracking bundle={bundle} busy={busy} error={error} preparedPassport={preparedPassport} buildPassport={buildPassport} answerRequest={answerRequest} retryProcessing={retryProcessing} pick={pick} />;

  return <main className="site-shell"><Header compact/><section className="report-journey" style={{ '--journey-step': `"${String(stage).padStart(2,'0')}"` } as CSSProperties}>
    <header className="journey-heading"><div>{suppliedCaseId&&<NativeLink href="/cases">← {pick('All reports')}</NativeLink>}<p className="eyebrow">{pick('Easy Mode · guided demo')}</p><h1>{pick('We will help you report this')}</h1><p className="journey-subtitle">{pick(`Step ${stage} of 5 · About ${Math.max(1,6-stage)} minutes left`)}</p></div><div className={`draft-saved save-${saveState}`} role="status" aria-live="polite"><span>●</span>{saveLabel(saveState,lastSavedAt,pick)}</div></header>
    <GuidedHelp stage={stage} pick={pick}/>
    <nav className="report-steps" aria-label={pick('Report progress','रिपोर्ट प्रगति')}>{[pick('Protect yourself','अपनी सुरक्षा'),pick('Payment','भुगतान'),pick('Evidence','प्रमाण'),pick('Your story','आपकी बात'),pick('Review','समीक्षा')].map((label,index)=>{const unlocked=bundle.profile?5:bundle.resolutions.length?4:bundle.intake?3:Math.max(2,stage);return <button key={label} className={stage===index+1?'active':stage>index+1?'done':''} disabled={index+1>unlocked} onClick={()=>setStage(index+1)}><span>{stage>index+1?'✓':index+1}</span>{label}</button>})}</nav>
    {stage>2&&<button className="journey-back" onClick={()=>setStage(stage-1)}>← {pick('Back to the previous step','पिछले चरण पर वापस')}</button>}
    {stage===1&&<SafetyStage continueAction={()=>setStage(2)} pick={pick}/>}
    {stage===2&&<Triage value={intake} setValue={setIntake} save={saveIntake} back={()=>setStage(1)} busy={busy==='intake'} pick={pick}/>}
    {stage===3&&<EvidenceStage bundle={bundle} facts={facts} setFacts={setFacts} loadDemo={loadDemo} upload={uploadEvidence} remove={removeEvidence} continueAction={async()=>{await saveFacts();setStage(4);}} busy={busy} pick={pick}/>}
    {stage===4&&<ComplaintStage narrative={narrative} setNarrative={setNarrative} profile={profile} setProfile={setProfile} facts={facts} save={saveComplaint} busy={busy==='complaint'} pick={pick}/>}
    {stage===5&&<ReviewStage bundle={bundle} profile={profile} submit={submit} busy={busy==='submit'} back={()=>setStage(4)} reviewEvidence={()=>setStage(3)} pick={pick}/>}
    {pending&&<AnalysisDrawer pending={pending} setPending={setPending} confirm={confirmAnalysis} retry={retryAnalysis} pick={pick}/>} 
    {ocr&&<div className="ocr-overlay" role="status"><div><span>{Math.round(ocr.progress*100)}%</span><strong>{humanOcrStatus(ocr.status,pick)}</strong><progress value={ocr.progress} max={1}/><small>{pick('Your image stays on this device while FIRST30 reads it.','FIRST30 जब चित्र पढ़ता है तब यह इसी डिवाइस पर रहता है।')}</small><button onClick={()=>ocrController.current?.abort()}>{pick('Cancel','रद्द करें')}</button></div></div>}
    {error&&<div ref={errorRef} className="error-banner workspace-error" role="alert" tabIndex={-1}><strong>{pick('Please fix this first','पहले इसे ठीक करें')}</strong><span>{error}</span></div>}
  </section><SafetyFooter/></main>;
}

function Login({value,setValue,submit,busy,error,pick}:{value:{mobile:string;otp:string};setValue:(v:{mobile:string;otp:string})=>void;submit:()=>void;busy:boolean;error:string;pick:(en:string,hi:string)=>string}) {
  return <main className="site-shell"><Header compact/><section className="demo-login"><div>
    <p className="eyebrow">{pick('Guided demo sign-in','निर्देशित डेमो साइन-इन')}</p><h1>{pick('Continue as Sunita Sharma','सुनीता शर्मा के रूप में आगे बढ़ें')}</h1>
    <p>{pick('The number and code are already filled in. Simply press the large button below. No SMS is sent.','नंबर और कोड पहले से भरे हैं। नीचे बड़ा बटन दबाएँ। कोई SMS नहीं भेजा जाता।')}</p>
    <label>{pick('Demo mobile number','डेमो मोबाइल नंबर')}<input inputMode="tel" autoComplete="tel" value={value.mobile} onChange={(e)=>setValue({...value,mobile:e.target.value})}/></label>
    <label>{pick('Demo 6-digit code','डेमो 6-अंकीय कोड')}<input inputMode="numeric" autoComplete="one-time-code" value={value.otp} onChange={(e)=>setValue({...value,otp:e.target.value})}/></label>
    <div className="demo-credentials" aria-label={pick('Demo credentials','डेमो विवरण')}><span>90000 00000</span><span>Code 123456</span></div>
    <button className="primary-button login-primary" disabled={busy} onClick={()=>void submit()}>{busy?pick('Opening your report…','आपकी रिपोर्ट खुल रही है…'):pick('Start my report','मेरी रिपोर्ट शुरू करें')} →</button>
    {error&&<p className="login-error" role="alert">{error}</p>}<small>{pick('This is a FIRST30 demonstration using sample information. It is not a government login.','यह नमूना जानकारी वाला FIRST30 डेमो है। यह सरकारी लॉगिन नहीं है।')}</small>
  </div></section><SafetyFooter/></main>;
}
function Loading({text}:{text:string}){return <main className="site-shell"><Header compact/><div className="loading-state" role="status">{text}</div></main>}

function GuidedHelp({stage,pick}:{stage:number;pick:(a:string,b:string)=>string}) {
  const messages=[
    pick('First, take the urgent safety steps. You can continue even if you have not called yet.','पहले जरूरी सुरक्षा कदम उठाएँ। अगर आपने अभी कॉल नहीं किया है तब भी आगे बढ़ सकते हैं।'),
    pick('Enter the payment details you know. Screenshots can help check them next.','भुगतान की जितनी जानकारी पता है, दर्ज करें। अगले चरण में स्क्रीनशॉट से जाँच होगी।'),
    pick('Add screenshots or use the sample. The transaction reference is the bank’s unique payment number; the recipient ID shows where the money went. A conflict simply means two screenshots show different values.','स्क्रीनशॉट जोड़ें या नमूना उपयोग करें। लेन-देन संदर्भ बैंक का खास भुगतान नंबर है; प्राप्तकर्ता ID बताती है पैसा कहाँ गया। विरोध का अर्थ है कि दो चित्रों में अलग जानकारी है।'),
    pick('Tell us what happened in your own words. There is no short character limit.','अपनी भाषा में बताएँ कि क्या हुआ। कोई छोटी अक्षर सीमा नहीं है।'),
    pick('Check the important details once before creating your demo reference number.','अपना डेमो संदर्भ नंबर बनाने से पहले जरूरी जानकारी एक बार जाँच लें।'),
  ];
  const text=messages[Math.min(4,Math.max(0,stage-1))];
  return <aside className="guided-help"><span aria-hidden="true">i</span><p>{text}</p></aside>;
}

function SafetyStage({continueAction,pick}:{continueAction:()=>void;pick:(a:string,b:string)=>string}){return <section className="journey-panel safety-stage"><div className="stage-intro"><span>01</span><div><p className="eyebrow">{pick('Protect yourself first','पहले अपनी सुरक्षा')}</p><h2>{pick('Do these three things now','अभी ये तीन काम करें')}</h2></div></div><ol className="safety-checklist"><li><b>1</b><div><strong>{pick('Call 1930','1930 पर कॉल करें')}</strong><p>{pick('For a real incident, call as soon as possible. FIRST30 does not place the call for you.','वास्तविक घटना में जल्द से जल्द कॉल करें। FIRST30 आपकी ओर से कॉल नहीं करता।')}</p></div></li><li><b>2</b><div><strong>{pick('Contact your bank','अपने बैंक से संपर्क करें')}</strong><p>{pick('Use the trusted number printed on the card or official statement.','कार्ड या आधिकारिक स्टेटमेंट पर दिया विश्वसनीय नंबर उपयोग करें।')}</p></div></li><li><b>3</b><div><strong>{pick('Never share an OTP','OTP कभी साझा न करें')}</strong><p>{pick('Do not approve another payment request, even if someone says it will reverse the loss.','अगर कोई कहे कि नुकसान वापस होगा, तब भी नया भुगतान अनुरोध मंजूर न करें।')}</p></div></li></ol><button className="primary-button stage-action" onClick={continueAction}>{pick('I understand — continue','मैं समझ गया/गई — आगे बढ़ें')} →</button></section>}

function Triage({value,setValue,save,back,busy,pick}:{value:typeof INTAKE;setValue:(v:typeof INTAKE)=>void;save:()=>void;back:()=>void;busy:boolean;pick:(a:string,b:string)=>string}) {
  return <section className="journey-panel"><div className="stage-intro"><span>02</span><div><p className="eyebrow">{pick('Payment details','भुगतान विवरण')}</p><h2>{pick('Tell us about the lost payment','खोए हुए भुगतान के बारे में बताएँ')}</h2></div></div>
    <div className="form-grid"><label>{pick('What kind of fraud was it?','यह किस प्रकार की धोखाधड़ी थी?')}<select value={value.fraudType} onChange={(e)=>setValue({...value,fraudType:e.target.value})}><option value="fake_kyc">Fake KYC / impersonation</option><option value="vishing">Fraud call / vishing</option><option value="marketplace">Marketplace scam</option><option value="job_scam">Job scam</option><option value="investment">Investment scam</option><option value="other">Other financial fraud</option></select></label><label>{pick('How was the money paid?','पैसा कैसे दिया गया?')}<select value={value.channel} onChange={(e)=>setValue({...value,channel:e.target.value})}><option value="upi">UPI</option><option value="card">Card</option><option value="bank_transfer">Bank transfer</option><option value="wallet">Wallet</option></select></label><label>{pick('Amount lost in rupees','रुपयों में गई राशि')}<input type="number" inputMode="numeric" value={value.amount} onChange={(e)=>setValue({...value,amount:Number(e.target.value)})}/><small>{pick('For example: 18,499','उदाहरण: 18,499')}</small></label><label>{pick('Date and time of payment','भुगतान की तारीख और समय')}<input type="datetime-local" value={value.occurredAt} onChange={(e)=>setValue({...value,occurredAt:e.target.value})}/></label><label>{pick('How recently did it happen?','यह कितनी देर पहले हुआ?')}<select value={value.lossTiming} onChange={(e)=>setValue({...value,lossTiming:e.target.value})}><option value="under_30_minutes">Within 30 minutes</option><option value="today">Earlier today</option><option value="earlier">Before today</option></select></label></div>
    <div className="contact-checks"><label><input type="checkbox" checked={value.helplineContacted} onChange={(e)=>setValue({...value,helplineContacted:e.target.checked})}/>{pick('I have called 1930','मैंने 1930 पर कॉल किया है')}</label><label><input type="checkbox" checked={value.bankContacted} onChange={(e)=>setValue({...value,bankContacted:e.target.checked})}/>{pick('I have contacted my bank','मैंने अपने बैंक से संपर्क किया है')}</label></div>
    <div className="stage-controls"><button className="secondary-button" onClick={back}>{pick('Back','वापस')}</button><button className="primary-button stage-action" disabled={busy} onClick={()=>void save()}>{busy?pick('Saving safely…','सुरक्षित रूप से सहेजा जा रहा है…'):pick('Save and continue','सहेजें और आगे बढ़ें')} →</button></div>
  </section>;
}

function EvidenceStage({bundle,facts,setFacts,loadDemo,upload,remove,continueAction,busy,pick}:{bundle:Bundle;facts:Record<FactKey,Resolution>;setFacts:(v:Record<FactKey,Resolution>)=>void;loadDemo:()=>void;upload:(f:File,k:EvidenceKind,s?:boolean,a?:boolean,c?:boolean)=>Promise<Pending>;remove:(id:string)=>Promise<void>;continueAction:()=>Promise<void>;busy:string;pick:(a:string,b?:string)=>string}) {
  const locale: string = 'en';
  const [safeDataConfirmed,setSafeDataConfirmed]=useState(false);
  const [kitBusy,setKitBusy]=useState(false);
  async function downloadKit(){setKitBusy(true);try{await downloadDemoEvidenceKit();}finally{setKitBusy(false);}}
  return <section className="journey-panel evidence-stage">
    <div className="stage-intro"><span>03</span><div><p className="eyebrow">{pick('Check your screenshots','अपने स्क्रीनशॉट जाँचें')}</p><h2>{pick('Use the prepared case or test FIRST30 with your own safe images.','तैयार केस उपयोग करें या अपनी सुरक्षित तस्वीरों से FIRST30 जाँचें।')}</h2></div></div>
    <div className="evidence-choice-row">
      <button className="demo-set-button compact-demo" disabled={Boolean(busy)} onClick={()=>void loadDemo()}><strong>{busy==='demo'?pick('Reading sample screenshots…','नमूना स्क्रीनशॉट पढ़े जा रहे हैं…'):pick('Use prepared sample case','तैयार नमूना केस उपयोग करें')}</strong><small>{pick('Fastest judge demo · one known difference','सबसे तेज़ जज डेमो · एक जाना-पहचाना अंतर')}</small></button>
      <button className="demo-download-button" disabled={kitBusy} onClick={()=>void downloadKit()}><strong>{kitBusy?pick('Preparing files…','फ़ाइलें तैयार हो रही हैं…'):pick('Download demo files','डेमो फ़ाइलें डाउनलोड करें')}</strong><small>{pick('Upload them yourself to prove the real flow','असली प्रक्रिया दिखाने के लिए इन्हें खुद अपलोड करें')}</small></button>
    </div>
    <label className="safe-data-confirmation"><input type="checkbox" checked={safeDataConfirmed} onChange={(event)=>setSafeDataConfirmed(event.target.checked)}/><span><strong>{pick('I am using fictional or fully redacted test images','मैं काल्पनिक या पूरी तरह छिपाई गई परीक्षण तस्वीरें उपयोग कर रहा/रही हूँ')}</strong><small>{pick('Do not upload real IDs, account numbers, card details, OTPs or private evidence to this public hackathon demo.','इस सार्वजनिक हैकाथॉन डेमो में असली ID, खाता नंबर, कार्ड विवरण, OTP या निजी प्रमाण अपलोड न करें।')}</small></span></label>
    <div className="evidence-work-grid"><div className="evidence-upload-grid">{(['receipt','chat','call_log'] as EvidenceKind[]).map((kind)=>{const item=bundle.evidence.find((e)=>e.kind===kind);return <article key={kind} className={item?'complete':''}><strong>{pick(...KIND_COPY[kind])}</strong>{item?<><small>{String(item.filename)}</small><span>✓ {pick('Added and checked','जोड़ा और जाँचा गया')}</span><button type="button" className="remove-evidence" disabled={busy==='remove'} onClick={()=>void remove(String(item.id))}>{pick('Remove and replace','हटाएँ और बदलें')}</button></>:<label className={!safeDataConfirmed?'disabled':''}>+ {safeDataConfirmed?pick('Choose your test image','अपनी परीक्षण तस्वीर चुनें'):pick('Confirm safe test data first','पहले सुरक्षित परीक्षण डेटा की पुष्टि करें')}<input type="file" disabled={!safeDataConfirmed||Boolean(busy)} accept="image/png,image/jpeg,image/webp" onChange={(e)=>{const file=e.target.files?.[0];if(file)void upload(file,kind,false,false,true).catch(()=>{});e.target.value='';}}/></label>}</article>})}</div><div className="fact-resolution-board"><div className="fact-board-title"><strong>{pick('Important details found','मिली हुई जरूरी जानकारी')}</strong><span>{bundle.passport.counts.passed} ✓ · {bundle.passport.counts.conflicts} !</span></div>{FACTS.map((field)=>{const obs=bundle.observations.filter((item)=>item.field===field);return <label key={field}><span>{factLabel(field,locale)}<small>{facts[field].resolutionType==='evidence'?pick('Found in a screenshot','स्क्रीनशॉट में मिला'):facts[field].resolutionType==='unknown'?pick('I do not know','मुझे नहीं पता'):pick('Entered by you','आपके द्वारा लिखा')}</small></span><input value={facts[field].value} onChange={(e)=>setFacts({...facts,[field]:{field,value:e.target.value,normalizedValue:e.target.value,resolutionType:'manual',sourceEvidenceId:null}})}/><div>{obs.map((item)=><button type="button" key={`${item.evidenceId}-${item.normalizedValue}`} onClick={()=>setFacts({...facts,[field]:{field,value:item.value,normalizedValue:item.normalizedValue,resolutionType:'evidence',sourceEvidenceId:item.evidenceId}})}>{kindShort(item.evidenceKind)} · {item.value}</button>)}<button type="button" onClick={()=>setFacts({...facts,[field]:{field,value:'Unknown',normalizedValue:'unknown',resolutionType:'unknown',sourceEvidenceId:null}})}>{pick('I do not know','मुझे नहीं पता')}</button></div></label>})}</div></div>
    <div className="finding-summary"><strong>{pick('What needs your attention','किस जानकारी पर ध्यान दें')}</strong><span>{bundle.passport.coverage.present}/3 {pick('screenshot types added','स्क्रीनशॉट प्रकार जोड़े')}</span><span>{bundle.passport.counts.conflicts} {pick('differences to review','अंतर जाँचने हैं')}</span><span>{bundle.passport.counts.unknownFacts} {pick('details marked “I do not know”','जानकारी “मुझे नहीं पता” चुनी')}</span></div>
    <button className="primary-button stage-action" disabled={!bundle.evidence.length||Boolean(busy)} onClick={()=>void continueAction()}>{pick('Confirm details and continue','जानकारी पुष्ट कर आगे बढ़ें')} →</button>
  </section>;
}

function ComplaintStage({narrative,setNarrative,profile,setProfile,facts,save,busy,pick}:{narrative:string;setNarrative:(v:string)=>void;profile:typeof PROFILE;setProfile:(v:typeof PROFILE)=>void;facts:Record<FactKey,Resolution>;save:()=>void;busy:boolean;pick:(a:string,b:string)=>string}){return <section className="journey-panel"><div className="stage-intro"><span>04</span><div><p className="eyebrow">{pick('Complaint details','शिकायत विवरण')}</p><h2>{pick('Explain it naturally. FIRST30 structures it.','स्वाभाविक रूप से बताएँ। FIRST30 इसे व्यवस्थित करता है।')}</h2></div></div><div className="complaint-layout"><div><label className="narrative-label">{pick('What happened? No 200-character rule. Special characters are allowed.','क्या हुआ? 200-अक्षर नियम नहीं। विशेष अक्षर मान्य हैं।')}<textarea value={narrative} onChange={(e)=>setNarrative(e.target.value)}/><small>{narrative.length} {pick('characters','अक्षर')}</small></label><div className="confirmed-facts-strip">{FACTS.map((field)=><span key={field}><small>{field.replace('_',' ')}</small><strong>{facts[field].value}</strong></span>)}</div></div><fieldset className="profile-form"><legend>{pick('Fictional complainant profile','काल्पनिक शिकायतकर्ता प्रोफ़ाइल')}</legend>{Object.entries(profile).map(([key,value])=><label key={key}>{profileLabel(key,pick)}<input value={value} onChange={(e)=>setProfile({...profile,[key]:e.target.value})}/></label>)}</fieldset></div><button className="primary-button stage-action" disabled={busy||narrative.trim().length<30} onClick={()=>void save()}>{pick('Build complaint preview','शिकायत पूर्वावलोकन बनाएँ')} →</button></section>}

function ReviewStage({bundle,profile,submit,busy,back,reviewEvidence,pick}:{bundle:Bundle;profile:typeof PROFILE;submit:()=>void;busy:boolean;back:()=>void;reviewEvidence:()=>void;pick:(a:string,b?:string)=>string}) {
  const blockers=bundle.readiness.issues.filter((issue)=>issue.severity==='blocker');
  const amountChoices=[...new Map(bundle.observations.filter((item)=>item.field==='amount').map((item)=>[item.normalizedValue,item])).values()];
  const firstConflict=bundle.passport.checks.find((check)=>check.status==='conflict');
  const differenceLine=amountChoices.length>1
    ? amountChoices.slice(0,2).map((item)=>`${pick(kindShort(item.evidenceKind),item.evidenceKind==='receipt'?'रसीद':item.evidenceKind==='chat'?'चैट':'प्रमाण')} · ₹${Number(item.normalizedValue).toLocaleString('en-IN')}`).join('  ≠  ')
    : pick(firstConflict?.detailEn||'Open your screenshots to review the difference.',firstConflict?.detailHi||'अंतर जाँचने के लिए अपने स्क्रीनशॉट खोलें।');
  return <section className="journey-panel"><div className="stage-intro"><span>05</span><div><p className="eyebrow">{pick('Review your report','अपनी रिपोर्ट जाँचें')}</p><h2>{pick('Check everything once before you finish','पूरा करने से पहले सब कुछ एक बार जाँचें')}</h2></div></div><div className="submission-boundary"><strong>{pick('This is a demonstration','यह एक डेमो है')}</strong><p>{pick('Finishing creates a FIRST30 demo reference number. Nothing is sent to NCRP, police, a bank or any government system.','पूरा करने पर FIRST30 डेमो संदर्भ नंबर बनता है। NCRP, पुलिस, बैंक या किसी सरकारी सिस्टम को कुछ नहीं भेजा जाता।')}</p></div>{blockers.length>0&&<div className="review-readiness" role="alert"><strong>{pick('Please check these details before finishing','पूरा करने से पहले यह जानकारी जाँचें')}</strong><ul>{blockers.map((issue)=><li key={`${issue.field||'report'}-${issue.messageEn}`}>{pick(issue.messageEn,issue.messageHi)}</li>)}</ul></div>}<div className="review-grid"><article><span>{pick('What happened','क्या हुआ')}</span><h3>₹{Number(bundle.case.amount||0).toLocaleString('en-IN')} · {String(bundle.case.channel).replace('_',' ')}</h3><p>{String(bundle.case.narrative_input||'')}</p></article>{bundle.passport.counts.conflicts>0?<button type="button" className="review-conflict-card" onClick={reviewEvidence} aria-label={pick(`Review ${bundle.passport.counts.conflicts} evidence difference`,`प्रमाण में ${bundle.passport.counts.conflicts} अंतर जाँचें`)}><span>{pick('Screenshots · needs your review','स्क्रीनशॉट · आपकी जाँच जरूरी')}</span><h3>{bundle.evidence.length} {pick('files ·','फ़ाइलें ·')} {bundle.passport.counts.conflicts} {pick('difference found','अंतर मिला')}</h3><p className="review-difference-line">{differenceLine}</p><small>{pick('Review this difference and choose the correct detail','यह अंतर जाँचें और सही जानकारी चुनें')} →</small></button>:<article><span>{pick('Screenshots','स्क्रीनशॉट')}</span><h3>{bundle.evidence.length} {pick('files · no differences','फ़ाइलें · कोई अंतर नहीं')}</h3><p>{pick('The checked details agree across your screenshots.','आपके स्क्रीनशॉट में जाँची गई जानकारी मेल खाती है।')}</p></article>}<article><span>{pick('Your details','आपकी जानकारी')}</span><h3>{profile.fullName}</h3><p>{profile.district}, {profile.state} · {profile.mobile}</p></article><article><span>{pick('Complaint prepared')}</span><h3>{pick('English complaint')}</h3><p>{String(bundle.case.complaint_en||'').slice(0,220)}…</p></article></div><div className="review-actions"><button className="secondary-button" onClick={back}>{pick('Back to edit','संपादन पर वापस')}</button><button className="primary-button" disabled={busy||blockers.length>0} onClick={()=>void submit()}>{busy?pick('Creating your demo reference…','आपका डेमो संदर्भ बन रहा है…'):pick('Finish and create demo reference','पूरा करें और डेमो संदर्भ बनाएँ')} →</button></div></section>;
}

function Tracking({bundle,busy,error,preparedPassport,buildPassport,answerRequest,retryProcessing,pick}:{bundle:Bundle;busy:string;error:string;preparedPassport:PreparedPassport|null;buildPassport:()=>void;answerRequest:(file?:File,safeDataConfirmed?:boolean)=>void;retryProcessing:()=>void;pick:(a:string,b?:string)=>string}) {
  const locale: string = 'en';
  const open = bundle.requests.find((item) => item.status === 'open');
  const [processing, setProcessing] = useState<ProcessingReceipt | null>(null);
  const [processingError, setProcessingError] = useState('');
  const [receiptBusy, setReceiptBusy] = useState(false); const [receiptError, setReceiptError] = useState('');
  const [safeFollowup,setSafeFollowup]=useState(false);
  const [preparedReceipt, setPreparedReceipt] = useState<PreparedPassport | null>(null); const preparedReceiptUrl = useRef<string | null>(null);
  useEffect(() => () => { if (preparedReceiptUrl.current) URL.revokeObjectURL(preparedReceiptUrl.current); }, []);
  useEffect(() => {
    let active = true;
    void api<{ processing: ProcessingReceipt }>(`/api/cases/${String(bundle.case.id)}/processing`)
      .then((result) => { if (active) setProcessing(result.processing); })
      .catch(() => { if (active) setProcessingError(pick('We cannot show the save details right now. Your report is still safe.','हम अभी सहेजने की जानकारी नहीं दिखा सकते। आपकी रिपोर्ट सुरक्षित है।')); });
    return () => { active = false; };
  }, [bundle.case.id, bundle.case.revision, pick]);
  const simpleStatus = processing?.status === 'complete'
    ? pick('Your demo report is ready','आपकी डेमो रिपोर्ट तैयार है')
    : pick('Your report is saved and can continue safely','आपकी रिपोर्ट सहेजी गई है और सुरक्षित रूप से जारी रह सकती है');
  async function saveReceipt(){setReceiptBusy(true);setReceiptError('');try{const prepared=await downloadComplaintReceipt(bundle);if(preparedReceiptUrl.current)URL.revokeObjectURL(preparedReceiptUrl.current);preparedReceiptUrl.current=prepared.downloadUrl;setPreparedReceipt(prepared);}catch{setReceiptError(pick('The PDF could not be created. Please try again.'));}finally{setReceiptBusy(false);}}

  return <main className="site-shell"><Header compact/><section className="tracking-page">
    {error&&<div className="error-banner workspace-error" role="alert"><strong>{pick('This action could not be completed','यह कार्रवाई पूरी नहीं हो सकी')}</strong><span>{error}</span></div>}
    <header><p className="eyebrow">{pick('Track your demo report','अपनी डेमो रिपोर्ट देखें')}</p><span className="mock-badge">DEMO</span><h1>{simpleStatus}</h1><p>{pick('This reference number works only inside this FIRST30 demonstration. It is not an NCRP or police complaint number.','यह संदर्भ नंबर केवल इस FIRST30 डेमो में काम करता है। यह NCRP या पुलिस शिकायत नंबर नहीं है।')}</p><code>{String(bundle.submission?.acknowledgement)}</code><details className="term-help"><summary>{pick('What does this number mean?','इस नंबर का क्या मतलब है?')}</summary><p>{pick('Use it to recognise this saved demo report inside FIRST30. For a real incident, use the number given by the bank, 1930 or the official reporting service.','FIRST30 में इस सहेजी डेमो रिपोर्ट को पहचानने के लिए इसका उपयोग करें। वास्तविक घटना में बैंक, 1930 या आधिकारिक रिपोर्टिंग सेवा से मिला नंबर उपयोग करें।')}</p></details></header>
    <div className="tracking-grid"><section className="status-timeline"><h2>{pick('Your report progress','आपकी रिपोर्ट की प्रगति')}</h2>{bundle.events.map((event,index)=>{const copy=friendlyEvent(event,pick);return <article key={String(event.id)}><span>{index+1}</span><div><strong>{copy.title}</strong><p>{copy.detail}</p><time>{new Date(Number(event.created_at)).toLocaleString(locale==='hi'?'hi-IN':'en-IN')}</time></div></article>})}</section>
      <aside><div className="tracking-status"><span>{open?'!':'✓'}</span><strong>{open?pick('One more document is needed','एक और दस्तावेज़ चाहिए'):pick('The extra document was added','अतिरिक्त दस्तावेज़ जोड़ दिया गया')}</strong><p>{open?pick('Add a safe test bank statement showing the reported payment.','दर्ज भुगतान दिखाने वाला सुरक्षित परीक्षण बैंक स्टेटमेंट जोड़ें।'):pick('You have completed this demo follow-up.','आपने यह डेमो अगला कदम पूरा कर लिया है।')}</p>{open&&<div className="followup-choices"><button className="primary-button" disabled={Boolean(busy)} onClick={()=>void answerRequest()}>{busy==='followup'?pick('Reading the statement…','स्टेटमेंट पढ़ा जा रहा है…'):pick('Use prepared statement','तैयार स्टेटमेंट उपयोग करें')} →</button><label className="followup-safe-check"><input type="checkbox" checked={safeFollowup} onChange={(event)=>setSafeFollowup(event.target.checked)}/><span>{pick('My file is fictional or fully redacted','मेरी फ़ाइल काल्पनिक या पूरी तरह छिपाई गई है')}</span></label><label className={`secondary-button followup-upload ${!safeFollowup?'disabled':''}`}>{pick('Choose my test statement','अपना परीक्षण स्टेटमेंट चुनें')}<input type="file" disabled={!safeFollowup||Boolean(busy)} accept="image/png,image/jpeg,image/webp" onChange={(event)=>{const file=event.target.files?.[0];if(file)void answerRequest(file,true);event.target.value='';}}/></label></div>}</div>
        {processing?.status !== 'complete' && <button className="secondary-button process-retry" disabled={Boolean(busy)} onClick={()=>void retryProcessing()}>{busy==='process'?pick('Trying again safely…','सुरक्षित रूप से फिर प्रयास…'):pick('Continue preparing my report','मेरी रिपोर्ट तैयार करना जारी रखें')}</button>}
        <details className="processing-proof"><summary>{pick('How FIRST30 kept this report safe','FIRST30 ने इस रिपोर्ट को कैसे सुरक्षित रखा')}</summary>{processing ? <div><dl><div><dt>{pick('Save reference for support','मदद के लिए सेव संदर्भ')}</dt><dd><code>{processing.requestId || pick('Older saved report','पुरानी सहेजी रिपोर्ट')}</code></dd></div><div><dt>{pick('Report copy protected','रिपोर्ट कॉपी सुरक्षित')}</dt><dd>{processing.snapshotFrozen?'✓ '+pick('Yes','हाँ'):'—'}</dd></div><div><dt>{pick('Screenshots checked','स्क्रीनशॉट जाँचे')}</dt><dd>{processing.evidenceChecks.verified}/{processing.evidenceChecks.total}</dd></div><div><dt>{pick('Repeated tries handled safely','बार-बार प्रयास सुरक्षित रखे')}</dt><dd>{processing.retries}</dd></div><div><dt>{pick('Report history complete','रिपोर्ट इतिहास पूरा')}</dt><dd>{processing.audit.valid?'✓ '+pick('Yes','हाँ'):'! '+pick('Please review','कृपया जाँचें')}</dd></div></dl><ol>{processing.steps.map((step)=><li key={step.step_code}><span>{step.status==='complete'?'✓':'…'}</span><div><strong>{friendlyStep(step.step_code,pick)}</strong><small>{step.attempt_count>1?pick('Completed safely after trying again','दोबारा प्रयास के बाद सुरक्षित रूप से पूरा'):pick('Completed once','एक बार में पूरा')}</small></div></li>)}</ol><p className="mock-boundary">{pick('This is only a demonstration. Nothing was sent outside FIRST30.','यह केवल एक डेमो है। FIRST30 से बाहर कुछ नहीं भेजा गया।')}</p></div> : <p>{processingError || pick('Opening your save details…','आपकी सहेजी जानकारी खुल रही है…')}</p>}</details>
        <button className="build-passport-button" disabled={Boolean(busy)} onClick={()=>void buildPassport()}><span>{busy==='export'?pick('Preparing your complete report…','आपकी पूरी रिपोर्ट तैयार हो रही है…'):preparedPassport?pick('Prepare a fresh copy','नई कॉपी तैयार करें'):pick('Download my complete report','मेरी पूरी रिपोर्ट डाउनलोड करें')}</span><small>{pick('Includes your complaint, screenshots and case summary','इसमें आपकी शिकायत, स्क्रीनशॉट और केस सारांश शामिल हैं')}</small></button>{preparedPassport&&<a className="secondary-button passport-save-link" href={preparedPassport.downloadUrl} download={preparedPassport.filename}>{pick('Save the complete report','पूरी रिपोर्ट सहेजें')} ↓</a>}<button className="receipt-download-button" disabled={receiptBusy} onClick={()=>void saveReceipt()}><span className="receipt-file-icon">PDF</span><span><strong>{receiptBusy?pick('Preparing your receipt…'):pick('Download complaint receipt')}</strong><small>{pick('A clear English record')}</small></span><span aria-hidden="true">↓</span></button>{preparedReceipt&&<a className="receipt-save-link" href={preparedReceipt.downloadUrl} download={preparedReceipt.filename}>{pick('Save the receipt again')} ↓</a>}{receiptError&&<p className="receipt-error" role="alert">{receiptError}</p>}<NativeLink className="text-button" href="/verify">{pick('Check my downloaded report','मेरी डाउनलोड रिपोर्ट जाँचें')} →</NativeLink></aside></div>
  </section><SafetyFooter/></main>;
}

function friendlyStep(code:string,pick:(a:string,b:string)=>string){
  if(code==='validate_snapshot')return pick('Important report details were checked','रिपोर्ट की जरूरी जानकारी जाँची गई');
  if(code==='mock_dispatch')return pick('The demo report was prepared','डेमो रिपोर्ट तैयार की गई');
  return pick('Your demo reference number was added','आपका डेमो संदर्भ नंबर जोड़ा गया');
}

function friendlyEvent(event:Row,pick:(a:string,b:string)=>string){
  if(event.type==='submitted')return {title:pick('Demo report completed','डेमो रिपोर्ट पूरी हुई'),detail:pick('Your FIRST30 demo reference number was created. Nothing was sent outside FIRST30.','आपका FIRST30 डेमो संदर्भ नंबर बनाया गया। FIRST30 से बाहर कुछ नहीं भेजा गया।')};
  if(event.type==='action_required')return {title:pick('One more document is needed · Demo','एक और दस्तावेज़ चाहिए · डेमो'),detail:pick('Add the sample bank statement to complete the next step.','अगला कदम पूरा करने के लिए नमूना बैंक स्टेटमेंट जोड़ें।')};
  if(event.type==='evidence_received')return {title:pick('Extra document added · Demo','अतिरिक्त दस्तावेज़ जोड़ा गया · डेमो'),detail:pick('The sample bank statement was added to this demo report.','नमूना बैंक स्टेटमेंट इस डेमो रिपोर्ट में जोड़ा गया।')};
  return {title:pick(String(event.title_en||'Report updated'),String(event.title_hi||'रिपोर्ट अपडेट हुई')),detail:pick(String(event.detail_en||''),String(event.detail_hi||''))};
}

function AnalysisDrawer({pending,setPending,confirm,retry,pick}:{pending:Pending;setPending:(v:Pending|null)=>void;confirm:(v?:Pending)=>Promise<void>;retry:()=>Promise<void>;pick:(a:string,b:string)=>string}){return <div className="analysis-drawer" role="dialog" aria-modal="true"><div><p className="eyebrow">{pick('Check what FIRST30 found','FIRST30 ने जो पाया उसे जाँचें')}</p><h2>{pick('Does this match the text in your screenshot?','क्या यह आपके स्क्रीनशॉट के पाठ से मेल खाता है?')}</h2><p>{pending.filename} · {pending.ocrMethod==='manual'?pick('Text entered by you','आपके द्वारा लिखा पाठ'):pick('Read privately on this device','इस डिवाइस पर निजी रूप से पढ़ा गया')}</p>{pending.notice&&<div className="analysis-notice">{pick('The sample text was used because the image could not be read clearly. Please check it before continuing.','चित्र साफ़ नहीं पढ़ा जा सका, इसलिए नमूना पाठ उपयोग किया गया। आगे बढ़ने से पहले इसे जाँचें।')}</div>}<textarea value={pending.text} onChange={(e)=>{const analysed=analyseManualText(pending.kind,e.target.value);setPending({...pending,...analysed});}} placeholder={pick('Correct the text or type anything FIRST30 missed.','पाठ ठीक करें या FIRST30 से छूटी जानकारी लिखें।')}/><div className="observation-preview">{pending.observations.map((item,index)=><span key={`${item.field}-${index}`}>{pick(factLabel(item.field,'en'),factLabel(item.field,'hi'))}: {item.value}</span>)}</div><div className="drawer-actions"><button className="text-button" onClick={()=>void retry()}>{pick('Read the image again','चित्र फिर पढ़ें')}</button><button className="text-button" onClick={()=>setPending(null)}>{pick('Close','बंद करें')}</button><button className="primary-button" disabled={!pending.observations.length} onClick={()=>void confirm(pending)}>{pick('Yes, use these details','हाँ, यह जानकारी उपयोग करें')}</button></div></div></div>}

function unknownFacts(){return Object.fromEntries(FACTS.map((field)=>[field,{field,value:'Unknown',normalizedValue:'unknown',resolutionType:'unknown',sourceEvidenceId:null}])) as Record<FactKey,Resolution>}
function suggestFacts(bundle:Bundle){const result=unknownFacts();for(const field of FACTS){const saved=bundle.resolutions.find((item)=>item.field===field);const preferred=bundle.observations.find((item)=>item.field===field&&(field==='phone'?item.evidenceKind==='call_log':item.evidenceKind==='receipt'))||bundle.observations.find((item)=>item.field===field);if(saved)result[field]=saved;else if(preferred)result[field]={field,value:preferred.value,normalizedValue:preferred.normalizedValue,resolutionType:'evidence',sourceEvidenceId:preferred.evidenceId};}return result}
function factLabel(field:FactKey,_legacyLocale?:string){void _legacyLocale;const labels:Record<FactKey,string>={amount:'Amount',reference:'Transaction reference',recipient:'Recipient',institution:'Institution',phone:'Suspect phone',occurred_at:'Transaction time'};return labels[field]}
function kindShort(kind:string){return kind==='receipt'?'Receipt':kind==='chat'?'Chat':kind==='call_log'?'Call log':'Statement'}
function profileLabel(key:string,pick:(a:string,b:string)=>string){const labels:Record<string,[string,string]>={fullName:['Full name','पूरा नाम'],mobile:['Mobile','मोबाइल'],gender:['Gender','लिंग'],dateOfBirth:['Date of birth','जन्म तिथि'],relationName:['Parent / spouse name','माता-पिता / जीवनसाथी नाम'],address:['Address','पता'],state:['State','राज्य'],district:['District','जिला'],policeStation:['Police station','पुलिस स्टेशन'],pincode:['PIN code','पिन कोड']};return pick(...labels[key])}
function humanOcrStatus(status:string,pick:(a:string,b:string)=>string){if(status.includes('recognizing'))return pick('Reading the words in your image…','आपके चित्र के शब्द पढ़े जा रहे हैं…');if(status.includes('loading'))return pick('Getting the private image reader ready…','निजी चित्र रीडर तैयार हो रहा है…');return pick('Preparing to read your image…','आपका चित्र पढ़ने की तैयारी हो रही है…')}
function saveLabel(state:'idle'|'saving'|'saved'|'retrying'|'offline',savedAt:number|null,pick:(a:string,b?:string)=>string){if(state==='saving')return pick('Saving safely…');if(state==='retrying')return pick('Retrying safely…');if(state==='offline')return pick('Connection lost');if(state==='saved'&&savedAt)return `${pick('Saved at')} ${new Date(savedAt).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'})}`;return pick('Progress is saved')}
function message(error:unknown){return error instanceof Error?error.message:'Please try again.'}
